import { FormEvent, useEffect, useState } from 'react';
import { Database, Link2, Plus, RefreshCw, ShieldAlert } from 'lucide-react';
import { createPartnerCatalogConnection, loadPartnerCatalogHub, type PartnerCatalogHubData } from '../../services/operationsMvp';

export function PartnerCatalogWorkstation() {
  const [data, setData] = useState<PartnerCatalogHubData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [form, setForm] = useState({ providerCode: '', displayName: '', externalCatalogReference: '' });
  const [saving, setSaving] = useState(false);
  const refresh = async () => { setLoading(true); setError(''); try { setData(await loadPartnerCatalogHub()); } catch (cause) { setError(cause instanceof Error ? cause.message : '甲方商品池数据暂时无法读取'); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); setNotice(''); try { const connection = await createPartnerCatalogConnection(form); setData((current) => current ? { ...current, connections: [connection, ...current.connections] } : current); setForm({ providerCode: '', displayName: '', externalCatalogReference: '' }); setNotice('接入资料已保存为待配置状态；未连接外部目录，也未触发导入。'); } catch (cause) { setError(cause instanceof Error ? cause.message : '接入资料保存失败'); } finally { setSaving(false); } };
  return <section className="mx-auto max-w-[1600px] space-y-5 p-6">
    <header className="rounded-2xl bg-gradient-to-r from-[#2c1746] to-[#6a3159] px-6 py-5 text-white shadow-lg"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-fuchsia-200">Partner Catalog Integration</p><h1 className="mt-1 text-xl font-black">甲方商品池接入</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-fuchsia-50">读取商城现有商品池、服务端接入配置与同步记录。凭据不在页面输入或显示；缺少服务端配置时保持“待配置”。</p></div><button onClick={() => void refresh()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border border-white/25 bg-white/10 px-3 py-2 text-xs font-semibold hover:bg-white/20 disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />刷新真实数据</button></div></header>
    {error && <Message tone="error">{error}</Message>}{notice && <Message tone="success">{notice}</Message>}
    {loading ? <Loading /> : data ? <>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-base font-bold text-slate-900"><Link2 className="h-4 w-4 text-fuchsia-600" />接入配置</h2><p className="mt-1 text-xs text-slate-500">状态仅来自服务端连接记录；本页不会判断或声明外部商品源已经连接。</p>{data.connections.length ? <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.connections.map((connection) => <article key={connection.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-2"><div><h3 className="font-semibold text-slate-900">{connection.displayName}</h3><p className="mt-1 font-mono text-xs text-slate-500">{connection.providerCode}</p></div><Status value={connection.status} /></div><p className="mt-3 text-xs text-slate-600">目录参考：{connection.externalCatalogReference || '未登记'}</p><p className="mt-1 text-xs text-slate-500">最近检查：{formatDate(connection.lastCheckedAt)}</p></article>)}</div> : <Empty label="尚未登记甲方商品源。不会以示例连接或伪造同步记录替代真实数据。" />}
        {data.capabilities.canManageConnections && <form onSubmit={(event) => void submit(event)} className="mt-5 grid gap-3 border-t pt-5 md:grid-cols-2 xl:grid-cols-4"><Field label="服务商编码" value={form.providerCode} onChange={(value) => setForm({ ...form, providerCode: value })} placeholder="例如 partner_catalog" required /><Field label="显示名称" value={form.displayName} onChange={(value) => setForm({ ...form, displayName: value })} placeholder="已确认的甲方名称" required /><Field label="外部目录参考（可选）" value={form.externalCatalogReference} onChange={(value) => setForm({ ...form, externalCatalogReference: value })} placeholder="目录 ID 或接入单号" /><button disabled={saving} className="inline-flex h-10 items-center justify-center gap-2 self-end rounded-lg bg-fuchsia-700 px-4 text-xs font-bold text-white disabled:opacity-50"><Plus className="h-4 w-4" />{saving ? '正在保存' : '登记接入配置'}</button></form>}
      </section>
      <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-base font-bold text-slate-900"><Database className="h-4 w-4 text-fuchsia-600" />商城商品池读取</h2><p className="mt-1 text-xs text-slate-500">数据来自商城现有商品池，不代表已完成外部同步。</p>{data.catalogPools.length ? <div className="mt-4 divide-y">{data.catalogPools.map((pool) => <div key={pool.id} className="flex items-center justify-between gap-3 py-3"><div><strong className="text-sm text-slate-800">{pool.name}</strong><p className="mt-1 font-mono text-xs text-slate-500">{pool.code}</p></div><span className="text-xs text-slate-600">{pool.itemCount} 个真实 SKU · {pool.status}</span></div>)}</div> : <Empty label="暂无商城商品池记录。" />}</section>
        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-base font-bold text-slate-900">导入与同步记录</h2><p className="mt-1 text-xs text-slate-500">仅展示实际写入的同步运行记录；当前不提供外部同步写入。</p>{data.syncRuns.length ? <div className="mt-4 divide-y">{data.syncRuns.map((run) => <div key={run.id} className="py-3"><div className="flex items-center justify-between gap-3"><strong className="text-sm text-slate-800">{run.displayName}</strong><Status value={run.status} /></div><p className="mt-1 text-xs text-slate-600">来源 {run.sourceItemCount ?? '—'} 项 · 已导入 {run.importedItemCount ?? '—'} 项</p>{run.message && <p className="mt-1 text-xs text-slate-500">{run.message}</p>}</div>)}</div> : <Empty label="暂无实际同步记录；外部目录凭据或同步作业未配置。" />}</section></div>
    </> : <Empty label="未取得甲方商品池数据。请确认当前账号的商品或商业资源权限。" />}
  </section>;
}
function Field({ label, value, onChange, placeholder, required }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; required?: boolean }) { return <label className="text-xs font-semibold text-slate-700">{label}<input required={required} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 h-10 w-full rounded-lg border border-slate-300 px-3 text-sm font-normal outline-none focus:border-fuchsia-500" /></label>; }
function Status({ value }: { value: string }) { return <span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-700">{({ pending_credentials: '待配置服务端凭据', awaiting_approval: '待审批', active: '已启用', disabled: '已停用', error: '异常待处理', queued: '已排队', running: '运行中', succeeded: '已完成', failed: '失败', blocked: '已阻断' } as Record<string, string>)[value] ?? value}</span>; }
function Message({ tone, children }: { tone: 'error' | 'success'; children: string }) { return <p className={`rounded-xl border px-4 py-3 text-sm ${tone === 'error' ? 'border-red-200 bg-red-50 text-red-700' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{children}</p>; }
function Loading() { return <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">正在读取甲方商品池配置…</div>; }
function Empty({ label }: { label: string }) { return <div className="mt-4 rounded-xl border border-dashed border-slate-300 bg-slate-50 px-5 py-10 text-center text-sm text-slate-500"><ShieldAlert className="mx-auto mb-2 h-5 w-5 text-slate-400" />{label}</div>; }
function formatDate(value: string | null) { if (!value) return '尚未检查'; const date = new Date(value); return Number.isNaN(date.getTime()) ? '—' : date.toLocaleString('zh-CN'); }
